apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o9nqyelmn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o9nqyelmn-go 
  name: o9nqyelmn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: o9nqyelmn-go 
